/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.scada;
@org.apache.avro.specific.AvroGenerated
public enum AlertType implements org.apache.avro.generic.GenericEnumSymbol<AlertType> {
  VOLTAGE_HIGH, VOLTAGE_LOW, FREQUENCY_DEVIATION, OVERLOAD, PRESSURE_DROP, TEMPERATURE_HIGH, SENSOR_OFFLINE, POWER_IMBALANCE, EQUIPMENT_FAILURE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlertType\",\"namespace\":\"io.confluent.examples.scada\",\"symbols\":[\"VOLTAGE_HIGH\",\"VOLTAGE_LOW\",\"FREQUENCY_DEVIATION\",\"OVERLOAD\",\"PRESSURE_DROP\",\"TEMPERATURE_HIGH\",\"SENSOR_OFFLINE\",\"POWER_IMBALANCE\",\"EQUIPMENT_FAILURE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
