/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.scada;
@org.apache.avro.specific.AvroGenerated
public enum GridRegion implements org.apache.avro.generic.GenericEnumSymbol<GridRegion> {
  ERCOT, WECC, EASTERN, TEXAS, QUEBEC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GridRegion\",\"namespace\":\"io.confluent.examples.scada\",\"symbols\":[\"ERCOT\",\"WECC\",\"EASTERN\",\"TEXAS\",\"QUEBEC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
