/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.scada;
@org.apache.avro.specific.AvroGenerated
public enum MeasurementType implements org.apache.avro.generic.GenericEnumSymbol<MeasurementType> {
  VOLTAGE, CURRENT, FREQUENCY, POWER_ACTIVE, POWER_REACTIVE, POWER_FACTOR, PRESSURE, FLOW, TEMPERATURE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MeasurementType\",\"namespace\":\"io.confluent.examples.scada\",\"symbols\":[\"VOLTAGE\",\"CURRENT\",\"FREQUENCY\",\"POWER_ACTIVE\",\"POWER_REACTIVE\",\"POWER_FACTOR\",\"PRESSURE\",\"FLOW\",\"TEMPERATURE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
