/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.scada;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** SCADA alerts for anomalies and critical events in USA energy grid */
@org.apache.avro.specific.AvroGenerated
public class ScadaAlert extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9162953842555516899L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ScadaAlert\",\"namespace\":\"io.confluent.examples.scada\",\"doc\":\"SCADA alerts for anomalies and critical events in USA energy grid\",\"fields\":[{\"name\":\"alert_id\",\"type\":\"string\",\"doc\":\"Unique alert identifier (e.g., ALERT_20260403_001234)\"},{\"name\":\"sensor_id\",\"type\":\"string\",\"doc\":\"Sensor that triggered the alert\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Alert generation timestamp in milliseconds since epoch\"},{\"name\":\"severity\",\"type\":{\"type\":\"enum\",\"name\":\"AlertSeverity\",\"symbols\":[\"INFO\",\"WARNING\",\"CRITICAL\",\"EMERGENCY\"]},\"doc\":\"Alert severity level\"},{\"name\":\"alert_type\",\"type\":{\"type\":\"enum\",\"name\":\"AlertType\",\"symbols\":[\"VOLTAGE_HIGH\",\"VOLTAGE_LOW\",\"FREQUENCY_DEVIATION\",\"OVERLOAD\",\"PRESSURE_DROP\",\"TEMPERATURE_HIGH\",\"SENSOR_OFFLINE\",\"POWER_IMBALANCE\",\"EQUIPMENT_FAILURE\"]},\"doc\":\"Type of alert condition\"},{\"name\":\"message\",\"type\":\"string\",\"doc\":\"Human-readable alert message\"},{\"name\":\"measured_value\",\"type\":\"double\",\"doc\":\"The value that triggered the alert\"},{\"name\":\"threshold_value\",\"type\":\"double\",\"doc\":\"The threshold that was exceeded\"},{\"name\":\"zone_id\",\"type\":\"string\",\"doc\":\"Geographic zone where alert occurred\"},{\"name\":\"state\",\"type\":\"string\",\"doc\":\"US State code where alert occurred\"},{\"name\":\"resolved\",\"type\":\"boolean\",\"doc\":\"Whether the alert has been resolved\",\"default\":false},{\"name\":\"resolved_at\",\"type\":[\"null\",\"long\"],\"doc\":\"Timestamp when alert was resolved (null if still active)\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ScadaAlert> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ScadaAlert> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ScadaAlert> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ScadaAlert> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ScadaAlert> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ScadaAlert to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ScadaAlert from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ScadaAlert instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ScadaAlert fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique alert identifier (e.g., ALERT_20260403_001234) */
  private java.lang.CharSequence alert_id;
  /** Sensor that triggered the alert */
  private java.lang.CharSequence sensor_id;
  /** Alert generation timestamp in milliseconds since epoch */
  private long timestamp;
  /** Alert severity level */
  private io.confluent.examples.scada.AlertSeverity severity;
  /** Type of alert condition */
  private io.confluent.examples.scada.AlertType alert_type;
  /** Human-readable alert message */
  private java.lang.CharSequence message;
  /** The value that triggered the alert */
  private double measured_value;
  /** The threshold that was exceeded */
  private double threshold_value;
  /** Geographic zone where alert occurred */
  private java.lang.CharSequence zone_id;
  /** US State code where alert occurred */
  private java.lang.CharSequence state;
  /** Whether the alert has been resolved */
  private boolean resolved;
  /** Timestamp when alert was resolved (null if still active) */
  private java.lang.Long resolved_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ScadaAlert() {}

  /**
   * All-args constructor.
   * @param alert_id Unique alert identifier (e.g., ALERT_20260403_001234)
   * @param sensor_id Sensor that triggered the alert
   * @param timestamp Alert generation timestamp in milliseconds since epoch
   * @param severity Alert severity level
   * @param alert_type Type of alert condition
   * @param message Human-readable alert message
   * @param measured_value The value that triggered the alert
   * @param threshold_value The threshold that was exceeded
   * @param zone_id Geographic zone where alert occurred
   * @param state US State code where alert occurred
   * @param resolved Whether the alert has been resolved
   * @param resolved_at Timestamp when alert was resolved (null if still active)
   */
  public ScadaAlert(java.lang.CharSequence alert_id, java.lang.CharSequence sensor_id, java.lang.Long timestamp, io.confluent.examples.scada.AlertSeverity severity, io.confluent.examples.scada.AlertType alert_type, java.lang.CharSequence message, java.lang.Double measured_value, java.lang.Double threshold_value, java.lang.CharSequence zone_id, java.lang.CharSequence state, java.lang.Boolean resolved, java.lang.Long resolved_at) {
    this.alert_id = alert_id;
    this.sensor_id = sensor_id;
    this.timestamp = timestamp;
    this.severity = severity;
    this.alert_type = alert_type;
    this.message = message;
    this.measured_value = measured_value;
    this.threshold_value = threshold_value;
    this.zone_id = zone_id;
    this.state = state;
    this.resolved = resolved;
    this.resolved_at = resolved_at;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return alert_id;
    case 1: return sensor_id;
    case 2: return timestamp;
    case 3: return severity;
    case 4: return alert_type;
    case 5: return message;
    case 6: return measured_value;
    case 7: return threshold_value;
    case 8: return zone_id;
    case 9: return state;
    case 10: return resolved;
    case 11: return resolved_at;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: alert_id = (java.lang.CharSequence)value$; break;
    case 1: sensor_id = (java.lang.CharSequence)value$; break;
    case 2: timestamp = (java.lang.Long)value$; break;
    case 3: severity = (io.confluent.examples.scada.AlertSeverity)value$; break;
    case 4: alert_type = (io.confluent.examples.scada.AlertType)value$; break;
    case 5: message = (java.lang.CharSequence)value$; break;
    case 6: measured_value = (java.lang.Double)value$; break;
    case 7: threshold_value = (java.lang.Double)value$; break;
    case 8: zone_id = (java.lang.CharSequence)value$; break;
    case 9: state = (java.lang.CharSequence)value$; break;
    case 10: resolved = (java.lang.Boolean)value$; break;
    case 11: resolved_at = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'alert_id' field.
   * @return Unique alert identifier (e.g., ALERT_20260403_001234)
   */
  public java.lang.CharSequence getAlertId() {
    return alert_id;
  }


  /**
   * Sets the value of the 'alert_id' field.
   * Unique alert identifier (e.g., ALERT_20260403_001234)
   * @param value the value to set.
   */
  public void setAlertId(java.lang.CharSequence value) {
    this.alert_id = value;
  }

  /**
   * Gets the value of the 'sensor_id' field.
   * @return Sensor that triggered the alert
   */
  public java.lang.CharSequence getSensorId() {
    return sensor_id;
  }


  /**
   * Sets the value of the 'sensor_id' field.
   * Sensor that triggered the alert
   * @param value the value to set.
   */
  public void setSensorId(java.lang.CharSequence value) {
    this.sensor_id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Alert generation timestamp in milliseconds since epoch
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Alert generation timestamp in milliseconds since epoch
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'severity' field.
   * @return Alert severity level
   */
  public io.confluent.examples.scada.AlertSeverity getSeverity() {
    return severity;
  }


  /**
   * Sets the value of the 'severity' field.
   * Alert severity level
   * @param value the value to set.
   */
  public void setSeverity(io.confluent.examples.scada.AlertSeverity value) {
    this.severity = value;
  }

  /**
   * Gets the value of the 'alert_type' field.
   * @return Type of alert condition
   */
  public io.confluent.examples.scada.AlertType getAlertType() {
    return alert_type;
  }


  /**
   * Sets the value of the 'alert_type' field.
   * Type of alert condition
   * @param value the value to set.
   */
  public void setAlertType(io.confluent.examples.scada.AlertType value) {
    this.alert_type = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return Human-readable alert message
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * Human-readable alert message
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'measured_value' field.
   * @return The value that triggered the alert
   */
  public double getMeasuredValue() {
    return measured_value;
  }


  /**
   * Sets the value of the 'measured_value' field.
   * The value that triggered the alert
   * @param value the value to set.
   */
  public void setMeasuredValue(double value) {
    this.measured_value = value;
  }

  /**
   * Gets the value of the 'threshold_value' field.
   * @return The threshold that was exceeded
   */
  public double getThresholdValue() {
    return threshold_value;
  }


  /**
   * Sets the value of the 'threshold_value' field.
   * The threshold that was exceeded
   * @param value the value to set.
   */
  public void setThresholdValue(double value) {
    this.threshold_value = value;
  }

  /**
   * Gets the value of the 'zone_id' field.
   * @return Geographic zone where alert occurred
   */
  public java.lang.CharSequence getZoneId() {
    return zone_id;
  }


  /**
   * Sets the value of the 'zone_id' field.
   * Geographic zone where alert occurred
   * @param value the value to set.
   */
  public void setZoneId(java.lang.CharSequence value) {
    this.zone_id = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return US State code where alert occurred
   */
  public java.lang.CharSequence getState() {
    return state;
  }


  /**
   * Sets the value of the 'state' field.
   * US State code where alert occurred
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'resolved' field.
   * @return Whether the alert has been resolved
   */
  public boolean getResolved() {
    return resolved;
  }


  /**
   * Sets the value of the 'resolved' field.
   * Whether the alert has been resolved
   * @param value the value to set.
   */
  public void setResolved(boolean value) {
    this.resolved = value;
  }

  /**
   * Gets the value of the 'resolved_at' field.
   * @return Timestamp when alert was resolved (null if still active)
   */
  public java.lang.Long getResolvedAt() {
    return resolved_at;
  }


  /**
   * Sets the value of the 'resolved_at' field.
   * Timestamp when alert was resolved (null if still active)
   * @param value the value to set.
   */
  public void setResolvedAt(java.lang.Long value) {
    this.resolved_at = value;
  }

  /**
   * Creates a new ScadaAlert RecordBuilder.
   * @return A new ScadaAlert RecordBuilder
   */
  public static io.confluent.examples.scada.ScadaAlert.Builder newBuilder() {
    return new io.confluent.examples.scada.ScadaAlert.Builder();
  }

  /**
   * Creates a new ScadaAlert RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ScadaAlert RecordBuilder
   */
  public static io.confluent.examples.scada.ScadaAlert.Builder newBuilder(io.confluent.examples.scada.ScadaAlert.Builder other) {
    if (other == null) {
      return new io.confluent.examples.scada.ScadaAlert.Builder();
    } else {
      return new io.confluent.examples.scada.ScadaAlert.Builder(other);
    }
  }

  /**
   * Creates a new ScadaAlert RecordBuilder by copying an existing ScadaAlert instance.
   * @param other The existing instance to copy.
   * @return A new ScadaAlert RecordBuilder
   */
  public static io.confluent.examples.scada.ScadaAlert.Builder newBuilder(io.confluent.examples.scada.ScadaAlert other) {
    if (other == null) {
      return new io.confluent.examples.scada.ScadaAlert.Builder();
    } else {
      return new io.confluent.examples.scada.ScadaAlert.Builder(other);
    }
  }

  /**
   * RecordBuilder for ScadaAlert instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ScadaAlert>
    implements org.apache.avro.data.RecordBuilder<ScadaAlert> {

    /** Unique alert identifier (e.g., ALERT_20260403_001234) */
    private java.lang.CharSequence alert_id;
    /** Sensor that triggered the alert */
    private java.lang.CharSequence sensor_id;
    /** Alert generation timestamp in milliseconds since epoch */
    private long timestamp;
    /** Alert severity level */
    private io.confluent.examples.scada.AlertSeverity severity;
    /** Type of alert condition */
    private io.confluent.examples.scada.AlertType alert_type;
    /** Human-readable alert message */
    private java.lang.CharSequence message;
    /** The value that triggered the alert */
    private double measured_value;
    /** The threshold that was exceeded */
    private double threshold_value;
    /** Geographic zone where alert occurred */
    private java.lang.CharSequence zone_id;
    /** US State code where alert occurred */
    private java.lang.CharSequence state;
    /** Whether the alert has been resolved */
    private boolean resolved;
    /** Timestamp when alert was resolved (null if still active) */
    private java.lang.Long resolved_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.examples.scada.ScadaAlert.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.alert_id)) {
        this.alert_id = data().deepCopy(fields()[0].schema(), other.alert_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[1].schema(), other.sensor_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.severity)) {
        this.severity = data().deepCopy(fields()[3].schema(), other.severity);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.alert_type)) {
        this.alert_type = data().deepCopy(fields()[4].schema(), other.alert_type);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.message)) {
        this.message = data().deepCopy(fields()[5].schema(), other.message);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.measured_value)) {
        this.measured_value = data().deepCopy(fields()[6].schema(), other.measured_value);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.threshold_value)) {
        this.threshold_value = data().deepCopy(fields()[7].schema(), other.threshold_value);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.zone_id)) {
        this.zone_id = data().deepCopy(fields()[8].schema(), other.zone_id);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.state)) {
        this.state = data().deepCopy(fields()[9].schema(), other.state);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.resolved)) {
        this.resolved = data().deepCopy(fields()[10].schema(), other.resolved);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.resolved_at)) {
        this.resolved_at = data().deepCopy(fields()[11].schema(), other.resolved_at);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing ScadaAlert instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.examples.scada.ScadaAlert other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.alert_id)) {
        this.alert_id = data().deepCopy(fields()[0].schema(), other.alert_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[1].schema(), other.sensor_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.severity)) {
        this.severity = data().deepCopy(fields()[3].schema(), other.severity);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.alert_type)) {
        this.alert_type = data().deepCopy(fields()[4].schema(), other.alert_type);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.message)) {
        this.message = data().deepCopy(fields()[5].schema(), other.message);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.measured_value)) {
        this.measured_value = data().deepCopy(fields()[6].schema(), other.measured_value);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.threshold_value)) {
        this.threshold_value = data().deepCopy(fields()[7].schema(), other.threshold_value);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.zone_id)) {
        this.zone_id = data().deepCopy(fields()[8].schema(), other.zone_id);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.state)) {
        this.state = data().deepCopy(fields()[9].schema(), other.state);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.resolved)) {
        this.resolved = data().deepCopy(fields()[10].schema(), other.resolved);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.resolved_at)) {
        this.resolved_at = data().deepCopy(fields()[11].schema(), other.resolved_at);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'alert_id' field.
      * Unique alert identifier (e.g., ALERT_20260403_001234)
      * @return The value.
      */
    public java.lang.CharSequence getAlertId() {
      return alert_id;
    }


    /**
      * Sets the value of the 'alert_id' field.
      * Unique alert identifier (e.g., ALERT_20260403_001234)
      * @param value The value of 'alert_id'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setAlertId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.alert_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_id' field has been set.
      * Unique alert identifier (e.g., ALERT_20260403_001234)
      * @return True if the 'alert_id' field has been set, false otherwise.
      */
    public boolean hasAlertId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'alert_id' field.
      * Unique alert identifier (e.g., ALERT_20260403_001234)
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearAlertId() {
      alert_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sensor_id' field.
      * Sensor that triggered the alert
      * @return The value.
      */
    public java.lang.CharSequence getSensorId() {
      return sensor_id;
    }


    /**
      * Sets the value of the 'sensor_id' field.
      * Sensor that triggered the alert
      * @param value The value of 'sensor_id'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setSensorId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.sensor_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sensor_id' field has been set.
      * Sensor that triggered the alert
      * @return True if the 'sensor_id' field has been set, false otherwise.
      */
    public boolean hasSensorId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sensor_id' field.
      * Sensor that triggered the alert
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearSensorId() {
      sensor_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Alert generation timestamp in milliseconds since epoch
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Alert generation timestamp in milliseconds since epoch
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setTimestamp(long value) {
      validate(fields()[2], value);
      this.timestamp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Alert generation timestamp in milliseconds since epoch
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Alert generation timestamp in milliseconds since epoch
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'severity' field.
      * Alert severity level
      * @return The value.
      */
    public io.confluent.examples.scada.AlertSeverity getSeverity() {
      return severity;
    }


    /**
      * Sets the value of the 'severity' field.
      * Alert severity level
      * @param value The value of 'severity'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setSeverity(io.confluent.examples.scada.AlertSeverity value) {
      validate(fields()[3], value);
      this.severity = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'severity' field has been set.
      * Alert severity level
      * @return True if the 'severity' field has been set, false otherwise.
      */
    public boolean hasSeverity() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'severity' field.
      * Alert severity level
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearSeverity() {
      severity = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_type' field.
      * Type of alert condition
      * @return The value.
      */
    public io.confluent.examples.scada.AlertType getAlertType() {
      return alert_type;
    }


    /**
      * Sets the value of the 'alert_type' field.
      * Type of alert condition
      * @param value The value of 'alert_type'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setAlertType(io.confluent.examples.scada.AlertType value) {
      validate(fields()[4], value);
      this.alert_type = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_type' field has been set.
      * Type of alert condition
      * @return True if the 'alert_type' field has been set, false otherwise.
      */
    public boolean hasAlertType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'alert_type' field.
      * Type of alert condition
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearAlertType() {
      alert_type = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * Human-readable alert message
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * Human-readable alert message
      * @param value The value of 'message'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.message = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * Human-readable alert message
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'message' field.
      * Human-readable alert message
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearMessage() {
      message = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'measured_value' field.
      * The value that triggered the alert
      * @return The value.
      */
    public double getMeasuredValue() {
      return measured_value;
    }


    /**
      * Sets the value of the 'measured_value' field.
      * The value that triggered the alert
      * @param value The value of 'measured_value'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setMeasuredValue(double value) {
      validate(fields()[6], value);
      this.measured_value = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'measured_value' field has been set.
      * The value that triggered the alert
      * @return True if the 'measured_value' field has been set, false otherwise.
      */
    public boolean hasMeasuredValue() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'measured_value' field.
      * The value that triggered the alert
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearMeasuredValue() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'threshold_value' field.
      * The threshold that was exceeded
      * @return The value.
      */
    public double getThresholdValue() {
      return threshold_value;
    }


    /**
      * Sets the value of the 'threshold_value' field.
      * The threshold that was exceeded
      * @param value The value of 'threshold_value'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setThresholdValue(double value) {
      validate(fields()[7], value);
      this.threshold_value = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'threshold_value' field has been set.
      * The threshold that was exceeded
      * @return True if the 'threshold_value' field has been set, false otherwise.
      */
    public boolean hasThresholdValue() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'threshold_value' field.
      * The threshold that was exceeded
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearThresholdValue() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'zone_id' field.
      * Geographic zone where alert occurred
      * @return The value.
      */
    public java.lang.CharSequence getZoneId() {
      return zone_id;
    }


    /**
      * Sets the value of the 'zone_id' field.
      * Geographic zone where alert occurred
      * @param value The value of 'zone_id'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setZoneId(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.zone_id = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'zone_id' field has been set.
      * Geographic zone where alert occurred
      * @return True if the 'zone_id' field has been set, false otherwise.
      */
    public boolean hasZoneId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'zone_id' field.
      * Geographic zone where alert occurred
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearZoneId() {
      zone_id = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * US State code where alert occurred
      * @return The value.
      */
    public java.lang.CharSequence getState() {
      return state;
    }


    /**
      * Sets the value of the 'state' field.
      * US State code where alert occurred
      * @param value The value of 'state'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setState(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.state = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * US State code where alert occurred
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'state' field.
      * US State code where alert occurred
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearState() {
      state = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'resolved' field.
      * Whether the alert has been resolved
      * @return The value.
      */
    public boolean getResolved() {
      return resolved;
    }


    /**
      * Sets the value of the 'resolved' field.
      * Whether the alert has been resolved
      * @param value The value of 'resolved'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setResolved(boolean value) {
      validate(fields()[10], value);
      this.resolved = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'resolved' field has been set.
      * Whether the alert has been resolved
      * @return True if the 'resolved' field has been set, false otherwise.
      */
    public boolean hasResolved() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'resolved' field.
      * Whether the alert has been resolved
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearResolved() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'resolved_at' field.
      * Timestamp when alert was resolved (null if still active)
      * @return The value.
      */
    public java.lang.Long getResolvedAt() {
      return resolved_at;
    }


    /**
      * Sets the value of the 'resolved_at' field.
      * Timestamp when alert was resolved (null if still active)
      * @param value The value of 'resolved_at'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder setResolvedAt(java.lang.Long value) {
      validate(fields()[11], value);
      this.resolved_at = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'resolved_at' field has been set.
      * Timestamp when alert was resolved (null if still active)
      * @return True if the 'resolved_at' field has been set, false otherwise.
      */
    public boolean hasResolvedAt() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'resolved_at' field.
      * Timestamp when alert was resolved (null if still active)
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaAlert.Builder clearResolvedAt() {
      resolved_at = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ScadaAlert build() {
      try {
        ScadaAlert record = new ScadaAlert();
        record.alert_id = fieldSetFlags()[0] ? this.alert_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.sensor_id = fieldSetFlags()[1] ? this.sensor_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.timestamp = fieldSetFlags()[2] ? this.timestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.severity = fieldSetFlags()[3] ? this.severity : (io.confluent.examples.scada.AlertSeverity) defaultValue(fields()[3]);
        record.alert_type = fieldSetFlags()[4] ? this.alert_type : (io.confluent.examples.scada.AlertType) defaultValue(fields()[4]);
        record.message = fieldSetFlags()[5] ? this.message : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.measured_value = fieldSetFlags()[6] ? this.measured_value : (java.lang.Double) defaultValue(fields()[6]);
        record.threshold_value = fieldSetFlags()[7] ? this.threshold_value : (java.lang.Double) defaultValue(fields()[7]);
        record.zone_id = fieldSetFlags()[8] ? this.zone_id : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.state = fieldSetFlags()[9] ? this.state : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.resolved = fieldSetFlags()[10] ? this.resolved : (java.lang.Boolean) defaultValue(fields()[10]);
        record.resolved_at = fieldSetFlags()[11] ? this.resolved_at : (java.lang.Long) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ScadaAlert>
    WRITER$ = (org.apache.avro.io.DatumWriter<ScadaAlert>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ScadaAlert>
    READER$ = (org.apache.avro.io.DatumReader<ScadaAlert>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.alert_id);

    out.writeString(this.sensor_id);

    out.writeLong(this.timestamp);

    out.writeEnum(this.severity.ordinal());

    out.writeEnum(this.alert_type.ordinal());

    out.writeString(this.message);

    out.writeDouble(this.measured_value);

    out.writeDouble(this.threshold_value);

    out.writeString(this.zone_id);

    out.writeString(this.state);

    out.writeBoolean(this.resolved);

    if (this.resolved_at == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.resolved_at);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.alert_id = in.readString(this.alert_id instanceof Utf8 ? (Utf8)this.alert_id : null);

      this.sensor_id = in.readString(this.sensor_id instanceof Utf8 ? (Utf8)this.sensor_id : null);

      this.timestamp = in.readLong();

      this.severity = io.confluent.examples.scada.AlertSeverity.values()[in.readEnum()];

      this.alert_type = io.confluent.examples.scada.AlertType.values()[in.readEnum()];

      this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);

      this.measured_value = in.readDouble();

      this.threshold_value = in.readDouble();

      this.zone_id = in.readString(this.zone_id instanceof Utf8 ? (Utf8)this.zone_id : null);

      this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);

      this.resolved = in.readBoolean();

      if (in.readIndex() != 1) {
        in.readNull();
        this.resolved_at = null;
      } else {
        this.resolved_at = in.readLong();
      }

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.alert_id = in.readString(this.alert_id instanceof Utf8 ? (Utf8)this.alert_id : null);
          break;

        case 1:
          this.sensor_id = in.readString(this.sensor_id instanceof Utf8 ? (Utf8)this.sensor_id : null);
          break;

        case 2:
          this.timestamp = in.readLong();
          break;

        case 3:
          this.severity = io.confluent.examples.scada.AlertSeverity.values()[in.readEnum()];
          break;

        case 4:
          this.alert_type = io.confluent.examples.scada.AlertType.values()[in.readEnum()];
          break;

        case 5:
          this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          break;

        case 6:
          this.measured_value = in.readDouble();
          break;

        case 7:
          this.threshold_value = in.readDouble();
          break;

        case 8:
          this.zone_id = in.readString(this.zone_id instanceof Utf8 ? (Utf8)this.zone_id : null);
          break;

        case 9:
          this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
          break;

        case 10:
          this.resolved = in.readBoolean();
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.resolved_at = null;
          } else {
            this.resolved_at = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (alert_id == null ? 0 : alert_id.hashCode());
    result = 31 * result + (sensor_id == null ? 0 : sensor_id.hashCode());
    result = 31 * result + Long.hashCode(timestamp);
    result = 31 * result + (severity == null ? 0 : ((java.lang.Enum) severity).ordinal());
    result = 31 * result + (alert_type == null ? 0 : ((java.lang.Enum) alert_type).ordinal());
    result = 31 * result + (message == null ? 0 : message.hashCode());
    result = 31 * result + Double.hashCode(measured_value);
    result = 31 * result + Double.hashCode(threshold_value);
    result = 31 * result + (zone_id == null ? 0 : zone_id.hashCode());
    result = 31 * result + (state == null ? 0 : state.hashCode());
    result = 31 * result + Boolean.hashCode(resolved);
    result = 31 * result + (resolved_at == null ? 0 : resolved_at.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ScadaAlert)) {
      return false;
    }
    ScadaAlert other = (ScadaAlert) o;
    if (Utf8.compareSequences(this.alert_id, other.alert_id) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.sensor_id, other.sensor_id) != 0) {
      return false;
    }
    if (this.timestamp != other.timestamp) {
      return false;
    }
    if (!java.util.Objects.equals(this.severity, other.severity)) {
      return false;
    }
    if (!java.util.Objects.equals(this.alert_type, other.alert_type)) {
      return false;
    }
    if (Utf8.compareSequences(this.message, other.message) != 0) {
      return false;
    }
    if (this.measured_value != other.measured_value) {
      return false;
    }
    if (this.threshold_value != other.threshold_value) {
      return false;
    }
    if (Utf8.compareSequences(this.zone_id, other.zone_id) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.state, other.state) != 0) {
      return false;
    }
    if (this.resolved != other.resolved) {
      return false;
    }
    if (!java.util.Objects.equals(this.resolved_at, other.resolved_at)) {
      return false;
    }
    return true;
  }
}










