/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.scada;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** SCADA sensor telemetry data for energy grid monitoring in USA */
@org.apache.avro.specific.AvroGenerated
public class ScadaTelemetry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2859832354859492938L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ScadaTelemetry\",\"namespace\":\"io.confluent.examples.scada\",\"doc\":\"SCADA sensor telemetry data for energy grid monitoring in USA\",\"fields\":[{\"name\":\"sensor_id\",\"type\":\"string\",\"doc\":\"Unique identifier for the sensor (e.g., SENSOR_TX_001)\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Timestamp of the reading in milliseconds since epoch\"},{\"name\":\"measurement_type\",\"type\":{\"type\":\"enum\",\"name\":\"MeasurementType\",\"symbols\":[\"VOLTAGE\",\"CURRENT\",\"FREQUENCY\",\"POWER_ACTIVE\",\"POWER_REACTIVE\",\"POWER_FACTOR\",\"PRESSURE\",\"FLOW\",\"TEMPERATURE\"]},\"doc\":\"Type of measurement being recorded\"},{\"name\":\"value\",\"type\":\"double\",\"doc\":\"Measured value\"},{\"name\":\"unit\",\"type\":\"string\",\"doc\":\"Unit of measurement (kV, A, Hz, MW, MVAr, bar, m3/h, C)\"},{\"name\":\"latitude\",\"type\":\"double\",\"doc\":\"Sensor latitude coordinate (USA range: ~25 to ~49)\"},{\"name\":\"longitude\",\"type\":\"double\",\"doc\":\"Sensor longitude coordinate (USA range: ~-125 to ~-67)\"},{\"name\":\"zone_id\",\"type\":\"string\",\"doc\":\"Geographic zone identifier (e.g., ZONE_TX_CENTRAL, ZONE_CA_NORTH)\"},{\"name\":\"state\",\"type\":\"string\",\"doc\":\"US State code (e.g., TX, CA, NY, FL)\"},{\"name\":\"city\",\"type\":\"string\",\"doc\":\"City name where sensor is located\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"SensorStatus\",\"symbols\":[\"NORMAL\",\"WARNING\",\"CRITICAL\",\"OFFLINE\"]},\"doc\":\"Current operational status of the sensor\"},{\"name\":\"grid_region\",\"type\":{\"type\":\"enum\",\"name\":\"GridRegion\",\"symbols\":[\"ERCOT\",\"WECC\",\"EASTERN\",\"TEXAS\",\"QUEBEC\"]},\"doc\":\"Major grid interconnection region in North America\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ScadaTelemetry> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ScadaTelemetry> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ScadaTelemetry> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ScadaTelemetry> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ScadaTelemetry> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ScadaTelemetry to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ScadaTelemetry from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ScadaTelemetry instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ScadaTelemetry fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier for the sensor (e.g., SENSOR_TX_001) */
  private java.lang.CharSequence sensor_id;
  /** Timestamp of the reading in milliseconds since epoch */
  private long timestamp;
  /** Type of measurement being recorded */
  private io.confluent.examples.scada.MeasurementType measurement_type;
  /** Measured value */
  private double value;
  /** Unit of measurement (kV, A, Hz, MW, MVAr, bar, m3/h, C) */
  private java.lang.CharSequence unit;
  /** Sensor latitude coordinate (USA range: ~25 to ~49) */
  private double latitude;
  /** Sensor longitude coordinate (USA range: ~-125 to ~-67) */
  private double longitude;
  /** Geographic zone identifier (e.g., ZONE_TX_CENTRAL, ZONE_CA_NORTH) */
  private java.lang.CharSequence zone_id;
  /** US State code (e.g., TX, CA, NY, FL) */
  private java.lang.CharSequence state;
  /** City name where sensor is located */
  private java.lang.CharSequence city;
  /** Current operational status of the sensor */
  private io.confluent.examples.scada.SensorStatus status;
  /** Major grid interconnection region in North America */
  private io.confluent.examples.scada.GridRegion grid_region;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ScadaTelemetry() {}

  /**
   * All-args constructor.
   * @param sensor_id Unique identifier for the sensor (e.g., SENSOR_TX_001)
   * @param timestamp Timestamp of the reading in milliseconds since epoch
   * @param measurement_type Type of measurement being recorded
   * @param value Measured value
   * @param unit Unit of measurement (kV, A, Hz, MW, MVAr, bar, m3/h, C)
   * @param latitude Sensor latitude coordinate (USA range: ~25 to ~49)
   * @param longitude Sensor longitude coordinate (USA range: ~-125 to ~-67)
   * @param zone_id Geographic zone identifier (e.g., ZONE_TX_CENTRAL, ZONE_CA_NORTH)
   * @param state US State code (e.g., TX, CA, NY, FL)
   * @param city City name where sensor is located
   * @param status Current operational status of the sensor
   * @param grid_region Major grid interconnection region in North America
   */
  public ScadaTelemetry(java.lang.CharSequence sensor_id, java.lang.Long timestamp, io.confluent.examples.scada.MeasurementType measurement_type, java.lang.Double value, java.lang.CharSequence unit, java.lang.Double latitude, java.lang.Double longitude, java.lang.CharSequence zone_id, java.lang.CharSequence state, java.lang.CharSequence city, io.confluent.examples.scada.SensorStatus status, io.confluent.examples.scada.GridRegion grid_region) {
    this.sensor_id = sensor_id;
    this.timestamp = timestamp;
    this.measurement_type = measurement_type;
    this.value = value;
    this.unit = unit;
    this.latitude = latitude;
    this.longitude = longitude;
    this.zone_id = zone_id;
    this.state = state;
    this.city = city;
    this.status = status;
    this.grid_region = grid_region;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sensor_id;
    case 1: return timestamp;
    case 2: return measurement_type;
    case 3: return value;
    case 4: return unit;
    case 5: return latitude;
    case 6: return longitude;
    case 7: return zone_id;
    case 8: return state;
    case 9: return city;
    case 10: return status;
    case 11: return grid_region;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sensor_id = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: measurement_type = (io.confluent.examples.scada.MeasurementType)value$; break;
    case 3: value = (java.lang.Double)value$; break;
    case 4: unit = (java.lang.CharSequence)value$; break;
    case 5: latitude = (java.lang.Double)value$; break;
    case 6: longitude = (java.lang.Double)value$; break;
    case 7: zone_id = (java.lang.CharSequence)value$; break;
    case 8: state = (java.lang.CharSequence)value$; break;
    case 9: city = (java.lang.CharSequence)value$; break;
    case 10: status = (io.confluent.examples.scada.SensorStatus)value$; break;
    case 11: grid_region = (io.confluent.examples.scada.GridRegion)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sensor_id' field.
   * @return Unique identifier for the sensor (e.g., SENSOR_TX_001)
   */
  public java.lang.CharSequence getSensorId() {
    return sensor_id;
  }


  /**
   * Sets the value of the 'sensor_id' field.
   * Unique identifier for the sensor (e.g., SENSOR_TX_001)
   * @param value the value to set.
   */
  public void setSensorId(java.lang.CharSequence value) {
    this.sensor_id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Timestamp of the reading in milliseconds since epoch
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Timestamp of the reading in milliseconds since epoch
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'measurement_type' field.
   * @return Type of measurement being recorded
   */
  public io.confluent.examples.scada.MeasurementType getMeasurementType() {
    return measurement_type;
  }


  /**
   * Sets the value of the 'measurement_type' field.
   * Type of measurement being recorded
   * @param value the value to set.
   */
  public void setMeasurementType(io.confluent.examples.scada.MeasurementType value) {
    this.measurement_type = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return Measured value
   */
  public double getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * Measured value
   * @param value the value to set.
   */
  public void setValue(double value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'unit' field.
   * @return Unit of measurement (kV, A, Hz, MW, MVAr, bar, m3/h, C)
   */
  public java.lang.CharSequence getUnit() {
    return unit;
  }


  /**
   * Sets the value of the 'unit' field.
   * Unit of measurement (kV, A, Hz, MW, MVAr, bar, m3/h, C)
   * @param value the value to set.
   */
  public void setUnit(java.lang.CharSequence value) {
    this.unit = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return Sensor latitude coordinate (USA range: ~25 to ~49)
   */
  public double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * Sensor latitude coordinate (USA range: ~25 to ~49)
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return Sensor longitude coordinate (USA range: ~-125 to ~-67)
   */
  public double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * Sensor longitude coordinate (USA range: ~-125 to ~-67)
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'zone_id' field.
   * @return Geographic zone identifier (e.g., ZONE_TX_CENTRAL, ZONE_CA_NORTH)
   */
  public java.lang.CharSequence getZoneId() {
    return zone_id;
  }


  /**
   * Sets the value of the 'zone_id' field.
   * Geographic zone identifier (e.g., ZONE_TX_CENTRAL, ZONE_CA_NORTH)
   * @param value the value to set.
   */
  public void setZoneId(java.lang.CharSequence value) {
    this.zone_id = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return US State code (e.g., TX, CA, NY, FL)
   */
  public java.lang.CharSequence getState() {
    return state;
  }


  /**
   * Sets the value of the 'state' field.
   * US State code (e.g., TX, CA, NY, FL)
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return City name where sensor is located
   */
  public java.lang.CharSequence getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * City name where sensor is located
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return Current operational status of the sensor
   */
  public io.confluent.examples.scada.SensorStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * Current operational status of the sensor
   * @param value the value to set.
   */
  public void setStatus(io.confluent.examples.scada.SensorStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'grid_region' field.
   * @return Major grid interconnection region in North America
   */
  public io.confluent.examples.scada.GridRegion getGridRegion() {
    return grid_region;
  }


  /**
   * Sets the value of the 'grid_region' field.
   * Major grid interconnection region in North America
   * @param value the value to set.
   */
  public void setGridRegion(io.confluent.examples.scada.GridRegion value) {
    this.grid_region = value;
  }

  /**
   * Creates a new ScadaTelemetry RecordBuilder.
   * @return A new ScadaTelemetry RecordBuilder
   */
  public static io.confluent.examples.scada.ScadaTelemetry.Builder newBuilder() {
    return new io.confluent.examples.scada.ScadaTelemetry.Builder();
  }

  /**
   * Creates a new ScadaTelemetry RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ScadaTelemetry RecordBuilder
   */
  public static io.confluent.examples.scada.ScadaTelemetry.Builder newBuilder(io.confluent.examples.scada.ScadaTelemetry.Builder other) {
    if (other == null) {
      return new io.confluent.examples.scada.ScadaTelemetry.Builder();
    } else {
      return new io.confluent.examples.scada.ScadaTelemetry.Builder(other);
    }
  }

  /**
   * Creates a new ScadaTelemetry RecordBuilder by copying an existing ScadaTelemetry instance.
   * @param other The existing instance to copy.
   * @return A new ScadaTelemetry RecordBuilder
   */
  public static io.confluent.examples.scada.ScadaTelemetry.Builder newBuilder(io.confluent.examples.scada.ScadaTelemetry other) {
    if (other == null) {
      return new io.confluent.examples.scada.ScadaTelemetry.Builder();
    } else {
      return new io.confluent.examples.scada.ScadaTelemetry.Builder(other);
    }
  }

  /**
   * RecordBuilder for ScadaTelemetry instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ScadaTelemetry>
    implements org.apache.avro.data.RecordBuilder<ScadaTelemetry> {

    /** Unique identifier for the sensor (e.g., SENSOR_TX_001) */
    private java.lang.CharSequence sensor_id;
    /** Timestamp of the reading in milliseconds since epoch */
    private long timestamp;
    /** Type of measurement being recorded */
    private io.confluent.examples.scada.MeasurementType measurement_type;
    /** Measured value */
    private double value;
    /** Unit of measurement (kV, A, Hz, MW, MVAr, bar, m3/h, C) */
    private java.lang.CharSequence unit;
    /** Sensor latitude coordinate (USA range: ~25 to ~49) */
    private double latitude;
    /** Sensor longitude coordinate (USA range: ~-125 to ~-67) */
    private double longitude;
    /** Geographic zone identifier (e.g., ZONE_TX_CENTRAL, ZONE_CA_NORTH) */
    private java.lang.CharSequence zone_id;
    /** US State code (e.g., TX, CA, NY, FL) */
    private java.lang.CharSequence state;
    /** City name where sensor is located */
    private java.lang.CharSequence city;
    /** Current operational status of the sensor */
    private io.confluent.examples.scada.SensorStatus status;
    /** Major grid interconnection region in North America */
    private io.confluent.examples.scada.GridRegion grid_region;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.examples.scada.ScadaTelemetry.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[0].schema(), other.sensor_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.measurement_type)) {
        this.measurement_type = data().deepCopy(fields()[2].schema(), other.measurement_type);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.unit)) {
        this.unit = data().deepCopy(fields()[4].schema(), other.unit);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.latitude)) {
        this.latitude = data().deepCopy(fields()[5].schema(), other.latitude);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.longitude)) {
        this.longitude = data().deepCopy(fields()[6].schema(), other.longitude);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.zone_id)) {
        this.zone_id = data().deepCopy(fields()[7].schema(), other.zone_id);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.state)) {
        this.state = data().deepCopy(fields()[8].schema(), other.state);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.city)) {
        this.city = data().deepCopy(fields()[9].schema(), other.city);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.status)) {
        this.status = data().deepCopy(fields()[10].schema(), other.status);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.grid_region)) {
        this.grid_region = data().deepCopy(fields()[11].schema(), other.grid_region);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing ScadaTelemetry instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.examples.scada.ScadaTelemetry other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[0].schema(), other.sensor_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.measurement_type)) {
        this.measurement_type = data().deepCopy(fields()[2].schema(), other.measurement_type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.unit)) {
        this.unit = data().deepCopy(fields()[4].schema(), other.unit);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.latitude)) {
        this.latitude = data().deepCopy(fields()[5].schema(), other.latitude);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.longitude)) {
        this.longitude = data().deepCopy(fields()[6].schema(), other.longitude);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.zone_id)) {
        this.zone_id = data().deepCopy(fields()[7].schema(), other.zone_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.state)) {
        this.state = data().deepCopy(fields()[8].schema(), other.state);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.city)) {
        this.city = data().deepCopy(fields()[9].schema(), other.city);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.status)) {
        this.status = data().deepCopy(fields()[10].schema(), other.status);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.grid_region)) {
        this.grid_region = data().deepCopy(fields()[11].schema(), other.grid_region);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'sensor_id' field.
      * Unique identifier for the sensor (e.g., SENSOR_TX_001)
      * @return The value.
      */
    public java.lang.CharSequence getSensorId() {
      return sensor_id;
    }


    /**
      * Sets the value of the 'sensor_id' field.
      * Unique identifier for the sensor (e.g., SENSOR_TX_001)
      * @param value The value of 'sensor_id'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setSensorId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sensor_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sensor_id' field has been set.
      * Unique identifier for the sensor (e.g., SENSOR_TX_001)
      * @return True if the 'sensor_id' field has been set, false otherwise.
      */
    public boolean hasSensorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sensor_id' field.
      * Unique identifier for the sensor (e.g., SENSOR_TX_001)
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearSensorId() {
      sensor_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Timestamp of the reading in milliseconds since epoch
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Timestamp of the reading in milliseconds since epoch
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Timestamp of the reading in milliseconds since epoch
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Timestamp of the reading in milliseconds since epoch
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'measurement_type' field.
      * Type of measurement being recorded
      * @return The value.
      */
    public io.confluent.examples.scada.MeasurementType getMeasurementType() {
      return measurement_type;
    }


    /**
      * Sets the value of the 'measurement_type' field.
      * Type of measurement being recorded
      * @param value The value of 'measurement_type'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setMeasurementType(io.confluent.examples.scada.MeasurementType value) {
      validate(fields()[2], value);
      this.measurement_type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'measurement_type' field has been set.
      * Type of measurement being recorded
      * @return True if the 'measurement_type' field has been set, false otherwise.
      */
    public boolean hasMeasurementType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'measurement_type' field.
      * Type of measurement being recorded
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearMeasurementType() {
      measurement_type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * Measured value
      * @return The value.
      */
    public double getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * Measured value
      * @param value The value of 'value'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setValue(double value) {
      validate(fields()[3], value);
      this.value = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * Measured value
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'value' field.
      * Measured value
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearValue() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'unit' field.
      * Unit of measurement (kV, A, Hz, MW, MVAr, bar, m3/h, C)
      * @return The value.
      */
    public java.lang.CharSequence getUnit() {
      return unit;
    }


    /**
      * Sets the value of the 'unit' field.
      * Unit of measurement (kV, A, Hz, MW, MVAr, bar, m3/h, C)
      * @param value The value of 'unit'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setUnit(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.unit = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'unit' field has been set.
      * Unit of measurement (kV, A, Hz, MW, MVAr, bar, m3/h, C)
      * @return True if the 'unit' field has been set, false otherwise.
      */
    public boolean hasUnit() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'unit' field.
      * Unit of measurement (kV, A, Hz, MW, MVAr, bar, m3/h, C)
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearUnit() {
      unit = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * Sensor latitude coordinate (USA range: ~25 to ~49)
      * @return The value.
      */
    public double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * Sensor latitude coordinate (USA range: ~25 to ~49)
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setLatitude(double value) {
      validate(fields()[5], value);
      this.latitude = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * Sensor latitude coordinate (USA range: ~25 to ~49)
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'latitude' field.
      * Sensor latitude coordinate (USA range: ~25 to ~49)
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearLatitude() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * Sensor longitude coordinate (USA range: ~-125 to ~-67)
      * @return The value.
      */
    public double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * Sensor longitude coordinate (USA range: ~-125 to ~-67)
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setLongitude(double value) {
      validate(fields()[6], value);
      this.longitude = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * Sensor longitude coordinate (USA range: ~-125 to ~-67)
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'longitude' field.
      * Sensor longitude coordinate (USA range: ~-125 to ~-67)
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearLongitude() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'zone_id' field.
      * Geographic zone identifier (e.g., ZONE_TX_CENTRAL, ZONE_CA_NORTH)
      * @return The value.
      */
    public java.lang.CharSequence getZoneId() {
      return zone_id;
    }


    /**
      * Sets the value of the 'zone_id' field.
      * Geographic zone identifier (e.g., ZONE_TX_CENTRAL, ZONE_CA_NORTH)
      * @param value The value of 'zone_id'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setZoneId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.zone_id = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'zone_id' field has been set.
      * Geographic zone identifier (e.g., ZONE_TX_CENTRAL, ZONE_CA_NORTH)
      * @return True if the 'zone_id' field has been set, false otherwise.
      */
    public boolean hasZoneId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'zone_id' field.
      * Geographic zone identifier (e.g., ZONE_TX_CENTRAL, ZONE_CA_NORTH)
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearZoneId() {
      zone_id = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * US State code (e.g., TX, CA, NY, FL)
      * @return The value.
      */
    public java.lang.CharSequence getState() {
      return state;
    }


    /**
      * Sets the value of the 'state' field.
      * US State code (e.g., TX, CA, NY, FL)
      * @param value The value of 'state'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setState(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.state = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * US State code (e.g., TX, CA, NY, FL)
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'state' field.
      * US State code (e.g., TX, CA, NY, FL)
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearState() {
      state = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * City name where sensor is located
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * City name where sensor is located
      * @param value The value of 'city'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.city = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * City name where sensor is located
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'city' field.
      * City name where sensor is located
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearCity() {
      city = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * Current operational status of the sensor
      * @return The value.
      */
    public io.confluent.examples.scada.SensorStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * Current operational status of the sensor
      * @param value The value of 'status'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setStatus(io.confluent.examples.scada.SensorStatus value) {
      validate(fields()[10], value);
      this.status = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * Current operational status of the sensor
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'status' field.
      * Current operational status of the sensor
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearStatus() {
      status = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'grid_region' field.
      * Major grid interconnection region in North America
      * @return The value.
      */
    public io.confluent.examples.scada.GridRegion getGridRegion() {
      return grid_region;
    }


    /**
      * Sets the value of the 'grid_region' field.
      * Major grid interconnection region in North America
      * @param value The value of 'grid_region'.
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder setGridRegion(io.confluent.examples.scada.GridRegion value) {
      validate(fields()[11], value);
      this.grid_region = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'grid_region' field has been set.
      * Major grid interconnection region in North America
      * @return True if the 'grid_region' field has been set, false otherwise.
      */
    public boolean hasGridRegion() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'grid_region' field.
      * Major grid interconnection region in North America
      * @return This builder.
      */
    public io.confluent.examples.scada.ScadaTelemetry.Builder clearGridRegion() {
      grid_region = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ScadaTelemetry build() {
      try {
        ScadaTelemetry record = new ScadaTelemetry();
        record.sensor_id = fieldSetFlags()[0] ? this.sensor_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.measurement_type = fieldSetFlags()[2] ? this.measurement_type : (io.confluent.examples.scada.MeasurementType) defaultValue(fields()[2]);
        record.value = fieldSetFlags()[3] ? this.value : (java.lang.Double) defaultValue(fields()[3]);
        record.unit = fieldSetFlags()[4] ? this.unit : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.latitude = fieldSetFlags()[5] ? this.latitude : (java.lang.Double) defaultValue(fields()[5]);
        record.longitude = fieldSetFlags()[6] ? this.longitude : (java.lang.Double) defaultValue(fields()[6]);
        record.zone_id = fieldSetFlags()[7] ? this.zone_id : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.state = fieldSetFlags()[8] ? this.state : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.city = fieldSetFlags()[9] ? this.city : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.status = fieldSetFlags()[10] ? this.status : (io.confluent.examples.scada.SensorStatus) defaultValue(fields()[10]);
        record.grid_region = fieldSetFlags()[11] ? this.grid_region : (io.confluent.examples.scada.GridRegion) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ScadaTelemetry>
    WRITER$ = (org.apache.avro.io.DatumWriter<ScadaTelemetry>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ScadaTelemetry>
    READER$ = (org.apache.avro.io.DatumReader<ScadaTelemetry>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.sensor_id);

    out.writeLong(this.timestamp);

    out.writeEnum(this.measurement_type.ordinal());

    out.writeDouble(this.value);

    out.writeString(this.unit);

    out.writeDouble(this.latitude);

    out.writeDouble(this.longitude);

    out.writeString(this.zone_id);

    out.writeString(this.state);

    out.writeString(this.city);

    out.writeEnum(this.status.ordinal());

    out.writeEnum(this.grid_region.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sensor_id = in.readString(this.sensor_id instanceof Utf8 ? (Utf8)this.sensor_id : null);

      this.timestamp = in.readLong();

      this.measurement_type = io.confluent.examples.scada.MeasurementType.values()[in.readEnum()];

      this.value = in.readDouble();

      this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);

      this.latitude = in.readDouble();

      this.longitude = in.readDouble();

      this.zone_id = in.readString(this.zone_id instanceof Utf8 ? (Utf8)this.zone_id : null);

      this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);

      this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);

      this.status = io.confluent.examples.scada.SensorStatus.values()[in.readEnum()];

      this.grid_region = io.confluent.examples.scada.GridRegion.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sensor_id = in.readString(this.sensor_id instanceof Utf8 ? (Utf8)this.sensor_id : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.measurement_type = io.confluent.examples.scada.MeasurementType.values()[in.readEnum()];
          break;

        case 3:
          this.value = in.readDouble();
          break;

        case 4:
          this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);
          break;

        case 5:
          this.latitude = in.readDouble();
          break;

        case 6:
          this.longitude = in.readDouble();
          break;

        case 7:
          this.zone_id = in.readString(this.zone_id instanceof Utf8 ? (Utf8)this.zone_id : null);
          break;

        case 8:
          this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
          break;

        case 9:
          this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);
          break;

        case 10:
          this.status = io.confluent.examples.scada.SensorStatus.values()[in.readEnum()];
          break;

        case 11:
          this.grid_region = io.confluent.examples.scada.GridRegion.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (sensor_id == null ? 0 : sensor_id.hashCode());
    result = 31 * result + Long.hashCode(timestamp);
    result = 31 * result + (measurement_type == null ? 0 : ((java.lang.Enum) measurement_type).ordinal());
    result = 31 * result + Double.hashCode(value);
    result = 31 * result + (unit == null ? 0 : unit.hashCode());
    result = 31 * result + Double.hashCode(latitude);
    result = 31 * result + Double.hashCode(longitude);
    result = 31 * result + (zone_id == null ? 0 : zone_id.hashCode());
    result = 31 * result + (state == null ? 0 : state.hashCode());
    result = 31 * result + (city == null ? 0 : city.hashCode());
    result = 31 * result + (status == null ? 0 : ((java.lang.Enum) status).ordinal());
    result = 31 * result + (grid_region == null ? 0 : ((java.lang.Enum) grid_region).ordinal());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ScadaTelemetry)) {
      return false;
    }
    ScadaTelemetry other = (ScadaTelemetry) o;
    if (Utf8.compareSequences(this.sensor_id, other.sensor_id) != 0) {
      return false;
    }
    if (this.timestamp != other.timestamp) {
      return false;
    }
    if (!java.util.Objects.equals(this.measurement_type, other.measurement_type)) {
      return false;
    }
    if (this.value != other.value) {
      return false;
    }
    if (Utf8.compareSequences(this.unit, other.unit) != 0) {
      return false;
    }
    if (this.latitude != other.latitude) {
      return false;
    }
    if (this.longitude != other.longitude) {
      return false;
    }
    if (Utf8.compareSequences(this.zone_id, other.zone_id) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.state, other.state) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.city, other.city) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.status, other.status)) {
      return false;
    }
    if (!java.util.Objects.equals(this.grid_region, other.grid_region)) {
      return false;
    }
    return true;
  }
}










