/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.scada;
@org.apache.avro.specific.AvroGenerated
public enum SensorStatus implements org.apache.avro.generic.GenericEnumSymbol<SensorStatus> {
  NORMAL, WARNING, CRITICAL, OFFLINE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SensorStatus\",\"namespace\":\"io.confluent.examples.scada\",\"symbols\":[\"NORMAL\",\"WARNING\",\"CRITICAL\",\"OFFLINE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
