/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Air quality monitoring station data for Smart City Madrid */
@org.apache.avro.specific.AvroGenerated
public class AirQualityStation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2654628075030082821L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AirQualityStation\",\"namespace\":\"io.confluent.examples.smartcity\",\"doc\":\"Air quality monitoring station data for Smart City Madrid\",\"fields\":[{\"name\":\"station_id\",\"type\":\"string\",\"doc\":\"Unique identifier for the air quality station (e.g., AIR-CENTRO-001)\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Timestamp of the reading in milliseconds since epoch\"},{\"name\":\"district\",\"type\":\"string\",\"doc\":\"Madrid district where the station is located\"},{\"name\":\"location_name\",\"type\":\"string\",\"doc\":\"Human-readable location name (e.g., Plaza del Carmen, Parque del Retiro)\"},{\"name\":\"latitude\",\"type\":\"double\",\"doc\":\"Station latitude coordinate\"},{\"name\":\"longitude\",\"type\":\"double\",\"doc\":\"Station longitude coordinate\"},{\"name\":\"no2\",\"type\":\"double\",\"doc\":\"Nitrogen dioxide concentration in µg/m³ (limit: 40, bad: >100)\"},{\"name\":\"pm25\",\"type\":\"double\",\"doc\":\"PM2.5 particulate matter in µg/m³ (good: <12, moderate: 12-35, bad: >35)\"},{\"name\":\"pm10\",\"type\":\"double\",\"doc\":\"PM10 particulate matter in µg/m³ (good: <20, moderate: 20-50, bad: >50)\"},{\"name\":\"o3\",\"type\":\"double\",\"doc\":\"Ozone concentration in µg/m³\"},{\"name\":\"co\",\"type\":\"double\",\"doc\":\"Carbon monoxide concentration in mg/m³\"},{\"name\":\"aqi\",\"type\":\"int\",\"doc\":\"Air Quality Index (0-100 good, 100-200 moderate, >200 bad)\"},{\"name\":\"quality_level\",\"type\":{\"type\":\"enum\",\"name\":\"AirQualityLevel\",\"symbols\":[\"GOOD\",\"MODERATE\",\"UNHEALTHY_SENSITIVE\",\"UNHEALTHY\",\"VERY_UNHEALTHY\",\"HAZARDOUS\"]},\"doc\":\"Air quality classification level\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"StationStatus\",\"symbols\":[\"ONLINE\",\"OFFLINE\",\"MAINTENANCE\",\"ERROR\"]},\"doc\":\"Operational status of the station\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AirQualityStation> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AirQualityStation> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AirQualityStation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AirQualityStation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AirQualityStation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AirQualityStation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AirQualityStation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AirQualityStation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AirQualityStation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier for the air quality station (e.g., AIR-CENTRO-001) */
  private java.lang.CharSequence station_id;
  /** Timestamp of the reading in milliseconds since epoch */
  private long timestamp;
  /** Madrid district where the station is located */
  private java.lang.CharSequence district;
  /** Human-readable location name (e.g., Plaza del Carmen, Parque del Retiro) */
  private java.lang.CharSequence location_name;
  /** Station latitude coordinate */
  private double latitude;
  /** Station longitude coordinate */
  private double longitude;
  /** Nitrogen dioxide concentration in µg/m³ (limit: 40, bad: &gt;100) */
  private double no2;
  /** PM2.5 particulate matter in µg/m³ (good: &lt;12, moderate: 12-35, bad: &gt;35) */
  private double pm25;
  /** PM10 particulate matter in µg/m³ (good: &lt;20, moderate: 20-50, bad: &gt;50) */
  private double pm10;
  /** Ozone concentration in µg/m³ */
  private double o3;
  /** Carbon monoxide concentration in mg/m³ */
  private double co;
  /** Air Quality Index (0-100 good, 100-200 moderate, &gt;200 bad) */
  private int aqi;
  /** Air quality classification level */
  private io.confluent.examples.smartcity.AirQualityLevel quality_level;
  /** Operational status of the station */
  private io.confluent.examples.smartcity.StationStatus status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AirQualityStation() {}

  /**
   * All-args constructor.
   * @param station_id Unique identifier for the air quality station (e.g., AIR-CENTRO-001)
   * @param timestamp Timestamp of the reading in milliseconds since epoch
   * @param district Madrid district where the station is located
   * @param location_name Human-readable location name (e.g., Plaza del Carmen, Parque del Retiro)
   * @param latitude Station latitude coordinate
   * @param longitude Station longitude coordinate
   * @param no2 Nitrogen dioxide concentration in µg/m³ (limit: 40, bad: &gt;100)
   * @param pm25 PM2.5 particulate matter in µg/m³ (good: &lt;12, moderate: 12-35, bad: &gt;35)
   * @param pm10 PM10 particulate matter in µg/m³ (good: &lt;20, moderate: 20-50, bad: &gt;50)
   * @param o3 Ozone concentration in µg/m³
   * @param co Carbon monoxide concentration in mg/m³
   * @param aqi Air Quality Index (0-100 good, 100-200 moderate, &gt;200 bad)
   * @param quality_level Air quality classification level
   * @param status Operational status of the station
   */
  public AirQualityStation(java.lang.CharSequence station_id, java.lang.Long timestamp, java.lang.CharSequence district, java.lang.CharSequence location_name, java.lang.Double latitude, java.lang.Double longitude, java.lang.Double no2, java.lang.Double pm25, java.lang.Double pm10, java.lang.Double o3, java.lang.Double co, java.lang.Integer aqi, io.confluent.examples.smartcity.AirQualityLevel quality_level, io.confluent.examples.smartcity.StationStatus status) {
    this.station_id = station_id;
    this.timestamp = timestamp;
    this.district = district;
    this.location_name = location_name;
    this.latitude = latitude;
    this.longitude = longitude;
    this.no2 = no2;
    this.pm25 = pm25;
    this.pm10 = pm10;
    this.o3 = o3;
    this.co = co;
    this.aqi = aqi;
    this.quality_level = quality_level;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return station_id;
    case 1: return timestamp;
    case 2: return district;
    case 3: return location_name;
    case 4: return latitude;
    case 5: return longitude;
    case 6: return no2;
    case 7: return pm25;
    case 8: return pm10;
    case 9: return o3;
    case 10: return co;
    case 11: return aqi;
    case 12: return quality_level;
    case 13: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: station_id = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: district = (java.lang.CharSequence)value$; break;
    case 3: location_name = (java.lang.CharSequence)value$; break;
    case 4: latitude = (java.lang.Double)value$; break;
    case 5: longitude = (java.lang.Double)value$; break;
    case 6: no2 = (java.lang.Double)value$; break;
    case 7: pm25 = (java.lang.Double)value$; break;
    case 8: pm10 = (java.lang.Double)value$; break;
    case 9: o3 = (java.lang.Double)value$; break;
    case 10: co = (java.lang.Double)value$; break;
    case 11: aqi = (java.lang.Integer)value$; break;
    case 12: quality_level = (io.confluent.examples.smartcity.AirQualityLevel)value$; break;
    case 13: status = (io.confluent.examples.smartcity.StationStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'station_id' field.
   * @return Unique identifier for the air quality station (e.g., AIR-CENTRO-001)
   */
  public java.lang.CharSequence getStationId() {
    return station_id;
  }


  /**
   * Sets the value of the 'station_id' field.
   * Unique identifier for the air quality station (e.g., AIR-CENTRO-001)
   * @param value the value to set.
   */
  public void setStationId(java.lang.CharSequence value) {
    this.station_id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Timestamp of the reading in milliseconds since epoch
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Timestamp of the reading in milliseconds since epoch
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'district' field.
   * @return Madrid district where the station is located
   */
  public java.lang.CharSequence getDistrict() {
    return district;
  }


  /**
   * Sets the value of the 'district' field.
   * Madrid district where the station is located
   * @param value the value to set.
   */
  public void setDistrict(java.lang.CharSequence value) {
    this.district = value;
  }

  /**
   * Gets the value of the 'location_name' field.
   * @return Human-readable location name (e.g., Plaza del Carmen, Parque del Retiro)
   */
  public java.lang.CharSequence getLocationName() {
    return location_name;
  }


  /**
   * Sets the value of the 'location_name' field.
   * Human-readable location name (e.g., Plaza del Carmen, Parque del Retiro)
   * @param value the value to set.
   */
  public void setLocationName(java.lang.CharSequence value) {
    this.location_name = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return Station latitude coordinate
   */
  public double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * Station latitude coordinate
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return Station longitude coordinate
   */
  public double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * Station longitude coordinate
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'no2' field.
   * @return Nitrogen dioxide concentration in µg/m³ (limit: 40, bad: &gt;100)
   */
  public double getNo2() {
    return no2;
  }


  /**
   * Sets the value of the 'no2' field.
   * Nitrogen dioxide concentration in µg/m³ (limit: 40, bad: &gt;100)
   * @param value the value to set.
   */
  public void setNo2(double value) {
    this.no2 = value;
  }

  /**
   * Gets the value of the 'pm25' field.
   * @return PM2.5 particulate matter in µg/m³ (good: &lt;12, moderate: 12-35, bad: &gt;35)
   */
  public double getPm25() {
    return pm25;
  }


  /**
   * Sets the value of the 'pm25' field.
   * PM2.5 particulate matter in µg/m³ (good: &lt;12, moderate: 12-35, bad: &gt;35)
   * @param value the value to set.
   */
  public void setPm25(double value) {
    this.pm25 = value;
  }

  /**
   * Gets the value of the 'pm10' field.
   * @return PM10 particulate matter in µg/m³ (good: &lt;20, moderate: 20-50, bad: &gt;50)
   */
  public double getPm10() {
    return pm10;
  }


  /**
   * Sets the value of the 'pm10' field.
   * PM10 particulate matter in µg/m³ (good: &lt;20, moderate: 20-50, bad: &gt;50)
   * @param value the value to set.
   */
  public void setPm10(double value) {
    this.pm10 = value;
  }

  /**
   * Gets the value of the 'o3' field.
   * @return Ozone concentration in µg/m³
   */
  public double getO3() {
    return o3;
  }


  /**
   * Sets the value of the 'o3' field.
   * Ozone concentration in µg/m³
   * @param value the value to set.
   */
  public void setO3(double value) {
    this.o3 = value;
  }

  /**
   * Gets the value of the 'co' field.
   * @return Carbon monoxide concentration in mg/m³
   */
  public double getCo() {
    return co;
  }


  /**
   * Sets the value of the 'co' field.
   * Carbon monoxide concentration in mg/m³
   * @param value the value to set.
   */
  public void setCo(double value) {
    this.co = value;
  }

  /**
   * Gets the value of the 'aqi' field.
   * @return Air Quality Index (0-100 good, 100-200 moderate, &gt;200 bad)
   */
  public int getAqi() {
    return aqi;
  }


  /**
   * Sets the value of the 'aqi' field.
   * Air Quality Index (0-100 good, 100-200 moderate, &gt;200 bad)
   * @param value the value to set.
   */
  public void setAqi(int value) {
    this.aqi = value;
  }

  /**
   * Gets the value of the 'quality_level' field.
   * @return Air quality classification level
   */
  public io.confluent.examples.smartcity.AirQualityLevel getQualityLevel() {
    return quality_level;
  }


  /**
   * Sets the value of the 'quality_level' field.
   * Air quality classification level
   * @param value the value to set.
   */
  public void setQualityLevel(io.confluent.examples.smartcity.AirQualityLevel value) {
    this.quality_level = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return Operational status of the station
   */
  public io.confluent.examples.smartcity.StationStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * Operational status of the station
   * @param value the value to set.
   */
  public void setStatus(io.confluent.examples.smartcity.StationStatus value) {
    this.status = value;
  }

  /**
   * Creates a new AirQualityStation RecordBuilder.
   * @return A new AirQualityStation RecordBuilder
   */
  public static io.confluent.examples.smartcity.AirQualityStation.Builder newBuilder() {
    return new io.confluent.examples.smartcity.AirQualityStation.Builder();
  }

  /**
   * Creates a new AirQualityStation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AirQualityStation RecordBuilder
   */
  public static io.confluent.examples.smartcity.AirQualityStation.Builder newBuilder(io.confluent.examples.smartcity.AirQualityStation.Builder other) {
    if (other == null) {
      return new io.confluent.examples.smartcity.AirQualityStation.Builder();
    } else {
      return new io.confluent.examples.smartcity.AirQualityStation.Builder(other);
    }
  }

  /**
   * Creates a new AirQualityStation RecordBuilder by copying an existing AirQualityStation instance.
   * @param other The existing instance to copy.
   * @return A new AirQualityStation RecordBuilder
   */
  public static io.confluent.examples.smartcity.AirQualityStation.Builder newBuilder(io.confluent.examples.smartcity.AirQualityStation other) {
    if (other == null) {
      return new io.confluent.examples.smartcity.AirQualityStation.Builder();
    } else {
      return new io.confluent.examples.smartcity.AirQualityStation.Builder(other);
    }
  }

  /**
   * RecordBuilder for AirQualityStation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AirQualityStation>
    implements org.apache.avro.data.RecordBuilder<AirQualityStation> {

    /** Unique identifier for the air quality station (e.g., AIR-CENTRO-001) */
    private java.lang.CharSequence station_id;
    /** Timestamp of the reading in milliseconds since epoch */
    private long timestamp;
    /** Madrid district where the station is located */
    private java.lang.CharSequence district;
    /** Human-readable location name (e.g., Plaza del Carmen, Parque del Retiro) */
    private java.lang.CharSequence location_name;
    /** Station latitude coordinate */
    private double latitude;
    /** Station longitude coordinate */
    private double longitude;
    /** Nitrogen dioxide concentration in µg/m³ (limit: 40, bad: &gt;100) */
    private double no2;
    /** PM2.5 particulate matter in µg/m³ (good: &lt;12, moderate: 12-35, bad: &gt;35) */
    private double pm25;
    /** PM10 particulate matter in µg/m³ (good: &lt;20, moderate: 20-50, bad: &gt;50) */
    private double pm10;
    /** Ozone concentration in µg/m³ */
    private double o3;
    /** Carbon monoxide concentration in mg/m³ */
    private double co;
    /** Air Quality Index (0-100 good, 100-200 moderate, &gt;200 bad) */
    private int aqi;
    /** Air quality classification level */
    private io.confluent.examples.smartcity.AirQualityLevel quality_level;
    /** Operational status of the station */
    private io.confluent.examples.smartcity.StationStatus status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.examples.smartcity.AirQualityStation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.station_id)) {
        this.station_id = data().deepCopy(fields()[0].schema(), other.station_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.district)) {
        this.district = data().deepCopy(fields()[2].schema(), other.district);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.location_name)) {
        this.location_name = data().deepCopy(fields()[3].schema(), other.location_name);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.latitude)) {
        this.latitude = data().deepCopy(fields()[4].schema(), other.latitude);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.longitude)) {
        this.longitude = data().deepCopy(fields()[5].schema(), other.longitude);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.no2)) {
        this.no2 = data().deepCopy(fields()[6].schema(), other.no2);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.pm25)) {
        this.pm25 = data().deepCopy(fields()[7].schema(), other.pm25);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.pm10)) {
        this.pm10 = data().deepCopy(fields()[8].schema(), other.pm10);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.o3)) {
        this.o3 = data().deepCopy(fields()[9].schema(), other.o3);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.co)) {
        this.co = data().deepCopy(fields()[10].schema(), other.co);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.aqi)) {
        this.aqi = data().deepCopy(fields()[11].schema(), other.aqi);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.quality_level)) {
        this.quality_level = data().deepCopy(fields()[12].schema(), other.quality_level);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.status)) {
        this.status = data().deepCopy(fields()[13].schema(), other.status);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing AirQualityStation instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.examples.smartcity.AirQualityStation other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.station_id)) {
        this.station_id = data().deepCopy(fields()[0].schema(), other.station_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.district)) {
        this.district = data().deepCopy(fields()[2].schema(), other.district);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.location_name)) {
        this.location_name = data().deepCopy(fields()[3].schema(), other.location_name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.latitude)) {
        this.latitude = data().deepCopy(fields()[4].schema(), other.latitude);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.longitude)) {
        this.longitude = data().deepCopy(fields()[5].schema(), other.longitude);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.no2)) {
        this.no2 = data().deepCopy(fields()[6].schema(), other.no2);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.pm25)) {
        this.pm25 = data().deepCopy(fields()[7].schema(), other.pm25);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.pm10)) {
        this.pm10 = data().deepCopy(fields()[8].schema(), other.pm10);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.o3)) {
        this.o3 = data().deepCopy(fields()[9].schema(), other.o3);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.co)) {
        this.co = data().deepCopy(fields()[10].schema(), other.co);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.aqi)) {
        this.aqi = data().deepCopy(fields()[11].schema(), other.aqi);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.quality_level)) {
        this.quality_level = data().deepCopy(fields()[12].schema(), other.quality_level);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.status)) {
        this.status = data().deepCopy(fields()[13].schema(), other.status);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'station_id' field.
      * Unique identifier for the air quality station (e.g., AIR-CENTRO-001)
      * @return The value.
      */
    public java.lang.CharSequence getStationId() {
      return station_id;
    }


    /**
      * Sets the value of the 'station_id' field.
      * Unique identifier for the air quality station (e.g., AIR-CENTRO-001)
      * @param value The value of 'station_id'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setStationId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.station_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'station_id' field has been set.
      * Unique identifier for the air quality station (e.g., AIR-CENTRO-001)
      * @return True if the 'station_id' field has been set, false otherwise.
      */
    public boolean hasStationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'station_id' field.
      * Unique identifier for the air quality station (e.g., AIR-CENTRO-001)
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearStationId() {
      station_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Timestamp of the reading in milliseconds since epoch
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Timestamp of the reading in milliseconds since epoch
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Timestamp of the reading in milliseconds since epoch
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Timestamp of the reading in milliseconds since epoch
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'district' field.
      * Madrid district where the station is located
      * @return The value.
      */
    public java.lang.CharSequence getDistrict() {
      return district;
    }


    /**
      * Sets the value of the 'district' field.
      * Madrid district where the station is located
      * @param value The value of 'district'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setDistrict(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.district = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'district' field has been set.
      * Madrid district where the station is located
      * @return True if the 'district' field has been set, false otherwise.
      */
    public boolean hasDistrict() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'district' field.
      * Madrid district where the station is located
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearDistrict() {
      district = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'location_name' field.
      * Human-readable location name (e.g., Plaza del Carmen, Parque del Retiro)
      * @return The value.
      */
    public java.lang.CharSequence getLocationName() {
      return location_name;
    }


    /**
      * Sets the value of the 'location_name' field.
      * Human-readable location name (e.g., Plaza del Carmen, Parque del Retiro)
      * @param value The value of 'location_name'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setLocationName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.location_name = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'location_name' field has been set.
      * Human-readable location name (e.g., Plaza del Carmen, Parque del Retiro)
      * @return True if the 'location_name' field has been set, false otherwise.
      */
    public boolean hasLocationName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'location_name' field.
      * Human-readable location name (e.g., Plaza del Carmen, Parque del Retiro)
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearLocationName() {
      location_name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * Station latitude coordinate
      * @return The value.
      */
    public double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * Station latitude coordinate
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setLatitude(double value) {
      validate(fields()[4], value);
      this.latitude = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * Station latitude coordinate
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'latitude' field.
      * Station latitude coordinate
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearLatitude() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * Station longitude coordinate
      * @return The value.
      */
    public double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * Station longitude coordinate
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setLongitude(double value) {
      validate(fields()[5], value);
      this.longitude = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * Station longitude coordinate
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'longitude' field.
      * Station longitude coordinate
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearLongitude() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'no2' field.
      * Nitrogen dioxide concentration in µg/m³ (limit: 40, bad: &gt;100)
      * @return The value.
      */
    public double getNo2() {
      return no2;
    }


    /**
      * Sets the value of the 'no2' field.
      * Nitrogen dioxide concentration in µg/m³ (limit: 40, bad: &gt;100)
      * @param value The value of 'no2'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setNo2(double value) {
      validate(fields()[6], value);
      this.no2 = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'no2' field has been set.
      * Nitrogen dioxide concentration in µg/m³ (limit: 40, bad: &gt;100)
      * @return True if the 'no2' field has been set, false otherwise.
      */
    public boolean hasNo2() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'no2' field.
      * Nitrogen dioxide concentration in µg/m³ (limit: 40, bad: &gt;100)
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearNo2() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'pm25' field.
      * PM2.5 particulate matter in µg/m³ (good: &lt;12, moderate: 12-35, bad: &gt;35)
      * @return The value.
      */
    public double getPm25() {
      return pm25;
    }


    /**
      * Sets the value of the 'pm25' field.
      * PM2.5 particulate matter in µg/m³ (good: &lt;12, moderate: 12-35, bad: &gt;35)
      * @param value The value of 'pm25'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setPm25(double value) {
      validate(fields()[7], value);
      this.pm25 = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'pm25' field has been set.
      * PM2.5 particulate matter in µg/m³ (good: &lt;12, moderate: 12-35, bad: &gt;35)
      * @return True if the 'pm25' field has been set, false otherwise.
      */
    public boolean hasPm25() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'pm25' field.
      * PM2.5 particulate matter in µg/m³ (good: &lt;12, moderate: 12-35, bad: &gt;35)
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearPm25() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'pm10' field.
      * PM10 particulate matter in µg/m³ (good: &lt;20, moderate: 20-50, bad: &gt;50)
      * @return The value.
      */
    public double getPm10() {
      return pm10;
    }


    /**
      * Sets the value of the 'pm10' field.
      * PM10 particulate matter in µg/m³ (good: &lt;20, moderate: 20-50, bad: &gt;50)
      * @param value The value of 'pm10'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setPm10(double value) {
      validate(fields()[8], value);
      this.pm10 = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'pm10' field has been set.
      * PM10 particulate matter in µg/m³ (good: &lt;20, moderate: 20-50, bad: &gt;50)
      * @return True if the 'pm10' field has been set, false otherwise.
      */
    public boolean hasPm10() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'pm10' field.
      * PM10 particulate matter in µg/m³ (good: &lt;20, moderate: 20-50, bad: &gt;50)
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearPm10() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'o3' field.
      * Ozone concentration in µg/m³
      * @return The value.
      */
    public double getO3() {
      return o3;
    }


    /**
      * Sets the value of the 'o3' field.
      * Ozone concentration in µg/m³
      * @param value The value of 'o3'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setO3(double value) {
      validate(fields()[9], value);
      this.o3 = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'o3' field has been set.
      * Ozone concentration in µg/m³
      * @return True if the 'o3' field has been set, false otherwise.
      */
    public boolean hasO3() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'o3' field.
      * Ozone concentration in µg/m³
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearO3() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'co' field.
      * Carbon monoxide concentration in mg/m³
      * @return The value.
      */
    public double getCo() {
      return co;
    }


    /**
      * Sets the value of the 'co' field.
      * Carbon monoxide concentration in mg/m³
      * @param value The value of 'co'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setCo(double value) {
      validate(fields()[10], value);
      this.co = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'co' field has been set.
      * Carbon monoxide concentration in mg/m³
      * @return True if the 'co' field has been set, false otherwise.
      */
    public boolean hasCo() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'co' field.
      * Carbon monoxide concentration in mg/m³
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearCo() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'aqi' field.
      * Air Quality Index (0-100 good, 100-200 moderate, &gt;200 bad)
      * @return The value.
      */
    public int getAqi() {
      return aqi;
    }


    /**
      * Sets the value of the 'aqi' field.
      * Air Quality Index (0-100 good, 100-200 moderate, &gt;200 bad)
      * @param value The value of 'aqi'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setAqi(int value) {
      validate(fields()[11], value);
      this.aqi = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'aqi' field has been set.
      * Air Quality Index (0-100 good, 100-200 moderate, &gt;200 bad)
      * @return True if the 'aqi' field has been set, false otherwise.
      */
    public boolean hasAqi() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'aqi' field.
      * Air Quality Index (0-100 good, 100-200 moderate, &gt;200 bad)
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearAqi() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'quality_level' field.
      * Air quality classification level
      * @return The value.
      */
    public io.confluent.examples.smartcity.AirQualityLevel getQualityLevel() {
      return quality_level;
    }


    /**
      * Sets the value of the 'quality_level' field.
      * Air quality classification level
      * @param value The value of 'quality_level'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setQualityLevel(io.confluent.examples.smartcity.AirQualityLevel value) {
      validate(fields()[12], value);
      this.quality_level = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'quality_level' field has been set.
      * Air quality classification level
      * @return True if the 'quality_level' field has been set, false otherwise.
      */
    public boolean hasQualityLevel() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'quality_level' field.
      * Air quality classification level
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearQualityLevel() {
      quality_level = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * Operational status of the station
      * @return The value.
      */
    public io.confluent.examples.smartcity.StationStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * Operational status of the station
      * @param value The value of 'status'.
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder setStatus(io.confluent.examples.smartcity.StationStatus value) {
      validate(fields()[13], value);
      this.status = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * Operational status of the station
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'status' field.
      * Operational status of the station
      * @return This builder.
      */
    public io.confluent.examples.smartcity.AirQualityStation.Builder clearStatus() {
      status = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AirQualityStation build() {
      try {
        AirQualityStation record = new AirQualityStation();
        record.station_id = fieldSetFlags()[0] ? this.station_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.district = fieldSetFlags()[2] ? this.district : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.location_name = fieldSetFlags()[3] ? this.location_name : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.latitude = fieldSetFlags()[4] ? this.latitude : (java.lang.Double) defaultValue(fields()[4]);
        record.longitude = fieldSetFlags()[5] ? this.longitude : (java.lang.Double) defaultValue(fields()[5]);
        record.no2 = fieldSetFlags()[6] ? this.no2 : (java.lang.Double) defaultValue(fields()[6]);
        record.pm25 = fieldSetFlags()[7] ? this.pm25 : (java.lang.Double) defaultValue(fields()[7]);
        record.pm10 = fieldSetFlags()[8] ? this.pm10 : (java.lang.Double) defaultValue(fields()[8]);
        record.o3 = fieldSetFlags()[9] ? this.o3 : (java.lang.Double) defaultValue(fields()[9]);
        record.co = fieldSetFlags()[10] ? this.co : (java.lang.Double) defaultValue(fields()[10]);
        record.aqi = fieldSetFlags()[11] ? this.aqi : (java.lang.Integer) defaultValue(fields()[11]);
        record.quality_level = fieldSetFlags()[12] ? this.quality_level : (io.confluent.examples.smartcity.AirQualityLevel) defaultValue(fields()[12]);
        record.status = fieldSetFlags()[13] ? this.status : (io.confluent.examples.smartcity.StationStatus) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AirQualityStation>
    WRITER$ = (org.apache.avro.io.DatumWriter<AirQualityStation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AirQualityStation>
    READER$ = (org.apache.avro.io.DatumReader<AirQualityStation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.station_id);

    out.writeLong(this.timestamp);

    out.writeString(this.district);

    out.writeString(this.location_name);

    out.writeDouble(this.latitude);

    out.writeDouble(this.longitude);

    out.writeDouble(this.no2);

    out.writeDouble(this.pm25);

    out.writeDouble(this.pm10);

    out.writeDouble(this.o3);

    out.writeDouble(this.co);

    out.writeInt(this.aqi);

    out.writeEnum(this.quality_level.ordinal());

    out.writeEnum(this.status.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.station_id = in.readString(this.station_id instanceof Utf8 ? (Utf8)this.station_id : null);

      this.timestamp = in.readLong();

      this.district = in.readString(this.district instanceof Utf8 ? (Utf8)this.district : null);

      this.location_name = in.readString(this.location_name instanceof Utf8 ? (Utf8)this.location_name : null);

      this.latitude = in.readDouble();

      this.longitude = in.readDouble();

      this.no2 = in.readDouble();

      this.pm25 = in.readDouble();

      this.pm10 = in.readDouble();

      this.o3 = in.readDouble();

      this.co = in.readDouble();

      this.aqi = in.readInt();

      this.quality_level = io.confluent.examples.smartcity.AirQualityLevel.values()[in.readEnum()];

      this.status = io.confluent.examples.smartcity.StationStatus.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 14; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.station_id = in.readString(this.station_id instanceof Utf8 ? (Utf8)this.station_id : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.district = in.readString(this.district instanceof Utf8 ? (Utf8)this.district : null);
          break;

        case 3:
          this.location_name = in.readString(this.location_name instanceof Utf8 ? (Utf8)this.location_name : null);
          break;

        case 4:
          this.latitude = in.readDouble();
          break;

        case 5:
          this.longitude = in.readDouble();
          break;

        case 6:
          this.no2 = in.readDouble();
          break;

        case 7:
          this.pm25 = in.readDouble();
          break;

        case 8:
          this.pm10 = in.readDouble();
          break;

        case 9:
          this.o3 = in.readDouble();
          break;

        case 10:
          this.co = in.readDouble();
          break;

        case 11:
          this.aqi = in.readInt();
          break;

        case 12:
          this.quality_level = io.confluent.examples.smartcity.AirQualityLevel.values()[in.readEnum()];
          break;

        case 13:
          this.status = io.confluent.examples.smartcity.StationStatus.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (station_id == null ? 0 : station_id.hashCode());
    result = 31 * result + Long.hashCode(timestamp);
    result = 31 * result + (district == null ? 0 : district.hashCode());
    result = 31 * result + (location_name == null ? 0 : location_name.hashCode());
    result = 31 * result + Double.hashCode(latitude);
    result = 31 * result + Double.hashCode(longitude);
    result = 31 * result + Double.hashCode(no2);
    result = 31 * result + Double.hashCode(pm25);
    result = 31 * result + Double.hashCode(pm10);
    result = 31 * result + Double.hashCode(o3);
    result = 31 * result + Double.hashCode(co);
    result = 31 * result + Integer.hashCode(aqi);
    result = 31 * result + (quality_level == null ? 0 : ((java.lang.Enum) quality_level).ordinal());
    result = 31 * result + (status == null ? 0 : ((java.lang.Enum) status).ordinal());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof AirQualityStation)) {
      return false;
    }
    AirQualityStation other = (AirQualityStation) o;
    if (Utf8.compareSequences(this.station_id, other.station_id) != 0) {
      return false;
    }
    if (this.timestamp != other.timestamp) {
      return false;
    }
    if (Utf8.compareSequences(this.district, other.district) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.location_name, other.location_name) != 0) {
      return false;
    }
    if (this.latitude != other.latitude) {
      return false;
    }
    if (this.longitude != other.longitude) {
      return false;
    }
    if (this.no2 != other.no2) {
      return false;
    }
    if (this.pm25 != other.pm25) {
      return false;
    }
    if (this.pm10 != other.pm10) {
      return false;
    }
    if (this.o3 != other.o3) {
      return false;
    }
    if (this.co != other.co) {
      return false;
    }
    if (this.aqi != other.aqi) {
      return false;
    }
    if (!java.util.Objects.equals(this.quality_level, other.quality_level)) {
      return false;
    }
    if (!java.util.Objects.equals(this.status, other.status)) {
      return false;
    }
    return true;
  }
}










