/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum AirQualityLevel implements org.apache.avro.generic.GenericEnumSymbol<AirQualityLevel> {
  GOOD, MODERATE, UNHEALTHY_SENSITIVE, UNHEALTHY, VERY_UNHEALTHY, HAZARDOUS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AirQualityLevel\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"GOOD\",\"MODERATE\",\"UNHEALTHY_SENSITIVE\",\"UNHEALTHY\",\"VERY_UNHEALTHY\",\"HAZARDOUS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
