/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum AlertType implements org.apache.avro.generic.GenericEnumSymbol<AlertType> {
  TRAFFIC_INCIDENT, TRAFFIC_CONGESTION, AIR_QUALITY_WARNING, AIR_QUALITY_CRITICAL, SERVICE_SLA_BREACH, BUS_OVERCROWDED, BUS_DELAYED, SENSOR_OFFLINE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlertType\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"TRAFFIC_INCIDENT\",\"TRAFFIC_CONGESTION\",\"AIR_QUALITY_WARNING\",\"AIR_QUALITY_CRITICAL\",\"SERVICE_SLA_BREACH\",\"BUS_OVERCROWDED\",\"BUS_DELAYED\",\"SENSOR_OFFLINE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
