/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum AlertSeverity implements org.apache.avro.generic.GenericEnumSymbol<AlertSeverity> {
  INFO, WARNING, CRITICAL, EMERGENCY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlertSeverity\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"INFO\",\"WARNING\",\"CRITICAL\",\"EMERGENCY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
