/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum BusStatus implements org.apache.avro.generic.GenericEnumSymbol<BusStatus> {
  IN_SERVICE, AT_STOP, OUT_OF_SERVICE, MAINTENANCE, OFFLINE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BusStatus\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"IN_SERVICE\",\"AT_STOP\",\"OUT_OF_SERVICE\",\"MAINTENANCE\",\"OFFLINE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
