/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum LocationType implements org.apache.avro.generic.GenericEnumSymbol<LocationType> {
  M30, MAIN_AVENUE, HIGHWAY_ACCESS, INTERSECTION, DOWNTOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LocationType\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"M30\",\"MAIN_AVENUE\",\"HIGHWAY_ACCESS\",\"INTERSECTION\",\"DOWNTOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
