/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum MadridDistrict implements org.apache.avro.generic.GenericEnumSymbol<MadridDistrict> {
  Centro, Arganzuela, Retiro, Salamanca, Chamartin, Tetuan, Chamberi, Fuencarral_El_Pardo, Moncloa_Aravaca, Latina, Carabanchel, Usera, Puente_de_Vallecas, Moratalaz, Ciudad_Lineal, Hortaleza, Villaverde, Villa_de_Vallecas, Vicalvaro, San_Blas_Canillejas, Barajas  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MadridDistrict\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"Centro\",\"Arganzuela\",\"Retiro\",\"Salamanca\",\"Chamartin\",\"Tetuan\",\"Chamberi\",\"Fuencarral_El_Pardo\",\"Moncloa_Aravaca\",\"Latina\",\"Carabanchel\",\"Usera\",\"Puente_de_Vallecas\",\"Moratalaz\",\"Ciudad_Lineal\",\"Hortaleza\",\"Villaverde\",\"Villa_de_Vallecas\",\"Vicalvaro\",\"San_Blas_Canillejas\",\"Barajas\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
