/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum Priority implements org.apache.avro.generic.GenericEnumSymbol<Priority> {
  BAJA, MEDIA, ALTA, URGENTE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Priority\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"BAJA\",\"MEDIA\",\"ALTA\",\"URGENTE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
