/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum ServiceStatus implements org.apache.avro.generic.GenericEnumSymbol<ServiceStatus> {
  ABIERTO, EN_PROCESO, PENDIENTE_VALIDACION, RESUELTO, CERRADO, RECHAZADO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ServiceStatus\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"ABIERTO\",\"EN_PROCESO\",\"PENDIENTE_VALIDACION\",\"RESUELTO\",\"CERRADO\",\"RECHAZADO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
