/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum ServiceCategory implements org.apache.avro.generic.GenericEnumSymbol<ServiceCategory> {
  ALUMBRADO_PUBLICO, LIMPIEZA_BASURA, BACHES_PAVIMENTO, PARQUES_JARDINES, MOBILIARIO_URBANO, OTROS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ServiceCategory\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"ALUMBRADO_PUBLICO\",\"LIMPIEZA_BASURA\",\"BACHES_PAVIMENTO\",\"PARQUES_JARDINES\",\"MOBILIARIO_URBANO\",\"OTROS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
