/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum StationStatus implements org.apache.avro.generic.GenericEnumSymbol<StationStatus> {
  ONLINE, OFFLINE, MAINTENANCE, ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"StationStatus\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"ONLINE\",\"OFFLINE\",\"MAINTENANCE\",\"ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
