/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum TrafficStatus implements org.apache.avro.generic.GenericEnumSymbol<TrafficStatus> {
  FLUID, MODERATE, CONGESTED, BLOCKED, OFFLINE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TrafficStatus\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"FLUID\",\"MODERATE\",\"CONGESTED\",\"BLOCKED\",\"OFFLINE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
