/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.smartcity;
@org.apache.avro.specific.AvroGenerated
public enum VehicleType implements org.apache.avro.generic.GenericEnumSymbol<VehicleType> {
  STANDARD, ARTICULATED, ELECTRIC, HYBRID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"VehicleType\",\"namespace\":\"io.confluent.examples.smartcity\",\"symbols\":[\"STANDARD\",\"ARTICULATED\",\"ELECTRIC\",\"HYBRID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
